/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/info.gltf 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

function Model() { 
  const { nodes, materials } = useGLTF('/models/info.gltf')


  return (
    <group dispose={null}>
      <group name="Scene">
        <group name="Curve" position={[0.02, -0.002, -0.082]} scale={11.236}>
          <mesh name="Curve_1" geometry={nodes.Curve_1.geometry} material={materials['Material.001']} />
          <mesh name="Curve_2" geometry={nodes.Curve_2.geometry} material={materials['Material.002']} />
          <mesh name="Curve_3" geometry={nodes.Curve_3.geometry} material={materials['Material.003']} />
        </group>
      </group>
    </group>
  )
} 
